export enum RoleType {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  AUDITOR = 'AUDITOR',
  CUSTOMER = 'CUSTOMER',
  SUPPORT = 'SUPPORT',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  REGULATORY_ANALYST = 'REGULATORY_ANALYST',
  COMPLIANCE_MANAGER = 'COMPLIANCE_MANAGER',
  COMPLIANCE_DIRECTOR = 'COMPLIANCE_DIRECTOR',
  FINANCE = 'FINANCE',
  HR = 'HR',
}
