export enum AuditEventType {
  USER_REGISTERED = 'user_registered',
  USER_VERIFIED = 'user_verified',
  USER_LOGIN = 'user_login',
  USER_LOGOUT = 'user_logout',
  PASSWORD_SET = 'password_set',
  PASSWORD_CHANGED = 'password_changed',
  PROFILE_UPDATED = 'profile_updated',
  ACCOUNT_CREATED = 'account_created',
  DEPOSIT = 'deposit',
  TRANSFER = 'transfer',
  WITHDRAWAL = 'withdrawal',
  ACCOUNT_FROZEN = 'account_frozen',
  ACCOUNT_CLOSED = 'account_closed',
  LOGIN_FAILED = 'login_failed',
  OTP_FAILED = 'otp_failed',
  // ── WO-004: Identity & Auth Core ──
  ROLE_CREATED = 'role_created',
  ROLE_ASSIGNED = 'role_assigned',
  ROLE_REVOKED = 'role_revoked',
  MFA_SETUP_STARTED = 'mfa_setup_started',
  MFA_VERIFIED = 'mfa_verified',
  MFA_FAILED = 'mfa_failed',
  MFA_USED_BACKUP_CODE = 'mfa_used_backup_code',
  MFA_DISABLED = 'mfa_disabled',
  PASSKEY_REGISTERED = 'passkey_registered',
  PASSKEY_AUTHENTICATED = 'passkey_authenticated',
  PASSKEY_AUTHENTICATION_FAILED = 'passkey_authentication_failed',
  PASSKEY_REVOKED = 'passkey_revoked',
  SESSION_REVOKED = 'session_revoked',
  SESSION_INVALIDATED = 'session_invalidated',
}
